FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_CASHEA_PUBLIC_KEY
ARG NEXT_PUBLIC_CASHEA_STORE_ID
ARG NEXT_PUBLIC_CASHEA_EXTERNAL_CLIENT_ID
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_CASHEA_PUBLIC_KEY=$NEXT_PUBLIC_CASHEA_PUBLIC_KEY
ENV NEXT_PUBLIC_CASHEA_STORE_ID=$NEXT_PUBLIC_CASHEA_STORE_ID
ENV NEXT_PUBLIC_CASHEA_EXTERNAL_CLIENT_ID=$NEXT_PUBLIC_CASHEA_EXTERNAL_CLIENT_ID

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
